/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.bookingDSL.Attribute;
import org.xtext.example.mydsl.bookingDSL.Booking;
import org.xtext.example.mydsl.bookingDSL.BookingDSLPackage;
import org.xtext.example.mydsl.bookingDSL.Customer;
import org.xtext.example.mydsl.bookingDSL.Declaration;
import org.xtext.example.mydsl.bookingDSL.Entity;
import org.xtext.example.mydsl.bookingDSL.Resource;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class BookingDSLValidator extends AbstractBookingDSLValidator {
	
	
	
	@Check
	public void warnIfNoDisplayName(Declaration declaration) {
		
		if(declaration instanceof Booking) {
			return;
		}
		
		var hasName = false;
		
		var members = declaration.getMembers();
		for(int i = 0; i < members.size(); i++) {
			var member = members.get(i);
			if(member instanceof Attribute) {
				var attriName = ((Attribute) member).getName();
				if(attriName.equals("name")) {
					hasName = true;
					
				}
			}
		}
		
		if(!hasName) {
			// Return warning that there are no name attribute
			warning("This declaration has no name", BookingDSLPackage.eINSTANCE.getBaseDeclaration_Name());
			return;
		}	
	}
	
	@Check
	public void errorIfDisplayNameIsNotString(Attribute attri) {
		
		var attriName = attri.getName();
		if(attriName.equals(("name"))) {
			var attriType = attri.getType().getLiteral();
			if(!attriType.equals("string")) {
				error("Attribute of type name can only be of type string", BookingDSLPackage.eINSTANCE.getAttribute_Name());
				return;
			}
		}
	}
	
	@Check
	public void warnIfAttributeNotCap(Attribute attri) {
		if(!Character.isUpperCase(attri.getName().charAt(0)))
			warning("Name should start with capital since methods are directly associated in generation", BookingDSLPackage.eINSTANCE.getAttribute_Name());
	}
	
	//equally important for decs
	@Check
	public void warnIfDecNotCap(Declaration dec) {
		if(!Character.isUpperCase(dec.getName().charAt(0)))
			warning("Name should start with capital since methods are directly associated in generation", BookingDSLPackage.eINSTANCE.getBaseDeclaration_Name());
	
	}
	
	@Check
	public void errorIfEntityHasNoRelationToResource(Entity ent) {
		
	}
	
	@Check
	public void errorIfResourceHasNoRelationToSchedule(Resource res) {
		
	}
	
	@Check
	public void errorIfBookingHasNoRelationToSchedule(Booking book) {
		
	}
	
	@Check
	public void errorOnCircularDependencies(Declaration dec) {
		
	}
	
	@Check
	public void errorOnCircularInheretence(Customer cust) {
		
	}
	
	@Check
	public void errorOnCircularInheretence(Resource res) {
		
	}
	
	//These if they make sense - double check
	@Check
	public void errorOnDuplicateNameAndType(Declaration dec) {
		
	}
	
	//Also check for attribute within same class? Not sure if relevant
	
	
}
