/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl;
import org.eclipse.xtext.resource.ILocationInFileProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BookingDSLRuntimeModule extends AbstractBookingDSLRuntimeModule {
	@Override
	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
		return BookingDSLLocationInFileProvider.class;
	}
}
