/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import customhovering.BookingDSLEObjectDocumentationProvider;
import customhovering.BookingDSLEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BookingDSLUiModule extends AbstractBookingDSLUiModule {

	public BookingDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider(){
		return BookingDSLEObjectHoverProvider.class;
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider(){
		return BookingDSLEObjectDocumentationProvider.class;
	}
}
