/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import static org.junit.Assert.assertTrue

@ExtendWith(InjectionExtension)
@InjectWith(BookingDSLInjectorProvider)
class BookingDSLParsingTest {
	@Test def void test(){
		assertTrue(true);
	}
	
	//Assert gen
	
	//Assert parser
	
	//Assert validation
}
